### ISSUE TITLE
`cfn-flow deploy` ignores `--help`

### ISSUE THREAD

**Issue by doismellburning** [kickstarter/cfn-flow#24]
As a CLI user, I expect a `--help` argument to, *ideally*, give me the help for a command, or at the least, give me an error message about an unexpected argument.

Instead today I experienced:

```
$ bundle exec cfn-flow deploy --help
Launching stack merchantredir-1475950289
# Snip
```

This was mildly distressing...!

Alas I don't Ruby well enough to be able to diagnose this myself, but browsing the Thor repo suggests that Thor _should_ respond sensibly to `--help`...

I believe I'm using latest and sensible versions:

```
$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    aws-sdk (2.6.5)
      aws-sdk-resources (= 2.6.5)
    aws-sdk-core (2.6.5)
      jmespath (~> 1.0)
    aws-sdk-resources (2.6.5)
      aws-sdk-core (= 2.6.5)
    cfn-flow (0.11.1)
      aws-sdk (~> 2.1, >= 2.1.8)
      multi_json
      thor (~> 0.18)
    jmespath (1.3.1)
    multi_json (1.12.1)
    thor (0.19.1)

PLATFORMS
  ruby

DEPENDENCIES
  cfn-flow

BUNDLED WITH
   1.12.5
```

**Comment by ktheory** [comment]
Hi @doismellburning,

Thanks for checking out `cfn-flow`. I hope you saw the [`cfn-flow help`](https://github.com/kickstarter/cfn-flow#usage) documentation.

If there's a way to add `--help` support in a generic way for each command (like Thor's `help` command currently does), I'd welcome that pull request. 😄 

Closing this issue for now. Feel free to re-open with a PR.
